name: Update Mirror Issue
on:
  issues:
    types:
      - closed
      - reopened

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TITLE_PREFIX: [duckdb/#${{ github.event.issue.number }}]

jobs:
  update_mirror_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get mirror issue number
        run: |
          echo "MIRROR_ISSUE_NUMBER=$(gh issue list --repo lnkuiper/external --json title,number --jq '.[]|select(.title | startswith("$TITLE_PREFIX")).number')" >> $GITHUB_ENV

      - name: Add comment with status to mirror issue
        run: |
          gh issue comment --repo lnkuiper/internal $MIRROR_ISSUE_NUMBER --body "The issue has been ${{ github.event.action }}."

      - name: Add closed label to mirror issue
        if: github.event.action == 'closed'
        run: |
          gh issue edit --repo lnkuiper/internal $MIRROR_ISSUE_NUMBER --add-label "closed" --remove-label "reopened"

      - name: Reopen mirror issue and add reopened label
        if: github.event.action == 'reopened'
        run: |
          if [ "$(gh issue view --repo lnkuiper/internal $MIRROR_ISSUE_NUMBER --json closed --jq '.closed')" = "true" ]; then
            gh issue reopen --repo lnkuiper/internal $MIRROR_ISSUE_NUMBER
          fi && \
          gh issue edit --repo lnkuiper/internal $MIRROR_ISSUE_NUMBER --add-label "reopened" --remove-label "closed"
